@TaskManagementApi_HostAddress = http://localhost:5000

GET {{TaskManagementApi_HostAddress}}/issues/
Accept: application/json

###
GET {{TaskManagementApi_HostAddress}}/users/
Accept: application/json

### Register a new user
POST {{TaskManagementApi_HostAddress}}/users/register
Content-Type: application/json

{
  "userName": "evan",
  "email": "evan@example.com",
  "password": "MySuperSecretPassword123@"
}

### Login a user
POST {{TaskManagementApi_HostAddress}}/users/login
Content-Type: application/json

{
  "userName": "",
  "email": "evan@example.com",
  "password": "MySuperSecretPassword123@"
}